name = "Storm"
author = "TheBossMagnus"
version = "0.1.4+fabric-1.20.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "894516b60ab628f43e43ccb6658439e23e81a6b380217fe0b85a53eab402a4f0"

[versions]
fabric = "0.15.6"
minecraft = "1.20.2"
