name = "Storm"
author = "TheBossMagnus"
version = "0.1.3+fabric-1.20.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1a434980cdd1a96a0a16ddb43664a7d832cd0cdec90fcd0a971627edbb53866"

[versions]
fabric = "0.15.6"
minecraft = "1.20.2"
