name = "Storm"
author = "TheBossMagnus"
version = "0.1.4+fabric-1.20.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26e51cbe9db43ad17d910c8bfa2cfa6e660a10cbe53189a459915b52d777110b"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"
