name = "Storm"
author = "TheBossMagnus"
version = "0.1.2+fabric-1.20.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9da487f3615f69f553fd5cc43f07d29a212ff6af07a8654222ffb013f9fa9265"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
