name = "Storm"
author = "TheBossMagnus"
version = "0.1.0+fabric-1.20.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8aeedeab325f8b8c07382fc32eb00256547ce4e3b239f50f004cba44db3577bb"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
