name = "Storm"
author = "TheBossMagnus"
version = "0.2.0+fabric-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "132e2552d16fd1acd885f8fd2415cd08cb2c0e15b5bfded1b695b592aae7e60b"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
