name = "Storm"
author = "TheBossMagnus"
version = "0.1.2+fabric-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ade69c6aa55754b2ba6da6ec68f493dfda6ec91fe2fd3ba79f9091f12a8dc9b"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
