name = "Storm"
author = "TheBossMagnus"
version = "0.2.0+fabric-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d73e581dd5b4bba4ff4271943f6d49bd03334cc665f2c2324ff0fc3a95ac72e"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
